config/routes.rb
Rails.application.routes.draw do

  get 'log_in'=>'sessions#new', as: 'log_in'
  get 'sign_up'=>'users#new', as: 'sign_up'

  root to:'users#new'
  resources :users
  resources :profiles
  resources :posts
  resources :images
  resources :sessions

end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :profile
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :images
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password

  has_many :posts
  has_many :profiles
  has_many :images

  validates_presence_of :password

  def self.authenticate(email,password)
    user=User.find_by_email(email)
    if user && user.password_hash==BCrypt::Engine.hash_secret(password,user.password_salt)
      user
    else
      p "auth failed"
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt=BCrypt::Engine.generate_salt
      self.password_hash=BCrypt::Engine.hash_secret(password,password_salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @image_upload=Image.new
  end

  def create
    @image_upload=Image.create(uploading_image)
  if  @image_upload.save
    redirect_to '/users'
  end
  end

  def uploading_image
      params.require(:image).permit(:avatar)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def new
    p params
    @new_profile=Profile.new
  end

  def create
    @new_profile=Profile.create(create_profile)
    @new_profile.save
    redirect_to 'users/index/'
  end

  def update
    @edit_profile=Profile.find(params[:id])
    @edit_profile.update_attributes(create_profile)
  end

  def create_profile
    params.require(:profile).permit(:user_id,:about,:name,:age)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    p params
    user=User.authenticate(params[:email],params[:password])
    if user
      p "working"
      session[:user_id]=user.id
       redirect_to users_path, notice: 'Logged In'

    else
      p "Abhiram"
      flash.now.alert="authentication failed"
    end
  end


  def destroy
    reset_session
    redirect_to 'log_in'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user_name=User.find(1)
    @user_profile=Profile.find_by_user_id(@user_name.id)
    @imagefile=Image.first
  end

 def new
    @new_user=User.new

 end

  def create
    @new_user=User.create(new_user)

    if @new_user.save
      redirect_to users_path
    end
  end

  def edit
      @edit_profile=Profile.find(:user_id => params[:id])

    respond_to do |format|
      format.js{}
    end
  end

  def update
    logger.debug(params)
     #@edit_profile=Profile.find(:user_id=>params[:id])
     @profile_image=Image.new
     @profile_image.update_attributes(:avatar=>params[:avatar],:user_id=>params[:id])
      @edit_profile.update_attributes(update_profile)



      redirect_to users_path
  end

  def update_profile
    params.require(:profile).permit(:user_id,:about,:name,:age,:avatar)
  end

  def update_image
    params.require(:image).permit(:avatar,:user_id)
  end

  def new_user
    params.require(:user).permit(:name,:email,:user_name,:password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/_uploadimage.html.erb
<%= form_for @image_upload, :html =>{:multipart=>true} do |image| %>
  <%= image.file_field :avatar %>
    <%= image.submit %>
<%end%>

app/views/images/index.html.erb
<%= link_to "upload image", new_image_path %>

app/views/images/new.html.erb
new image
<%= render 'uploadimage' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snetwork</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="navigation">
   <% if current_user %>
      Logged in as : <%= current_user.name %>
      <%= link_to "Logout", session_path(:id=>current_user),method: :delete %>
  <%else%>
      <%= link_to "Login", new_session_path %>
  <%end%>
</div>

<%= yield %>

</body>
</html>

app/views/profiles/_createprofile.html.erb
   <div class="newprofile">
     <%= form_for @new_profile do |f| %>
      <fieldset>

        <div class="control-group">
            <%= f.label :name %>
          <div class="controls">
            <%= f.text_field :name, class: 'form-control' %><br /><br />
          </div>
        </div>

        <div class="control-group">
          <%= f.label :age %>
          <div class="controls">
           <%= f.text_field :age,class: 'form-control' %><br /><br />
          </div>
        </div>

        <div class="control-group">
           <%= f.label :about %>
          <div class="controls">
             <%= f.text_field :about,class: 'form-control' %><br /><br />
          </div>
        </div>

        <div class="form-actions">
          <%= f.button :submit,:class=>"btn btn-xs btn-success" %>
        </div>
      </fieldset>

     <%end%>
   </div>

app/views/profiles/new.html.erb
<h4><strong><u>create profile</u></strong></h4><br>

<%= render 'createprofile' %>

app/views/users/_editprofile.html.erb
<div class="editprofile">
  <%= form_for @edit_profile,url:user_path(@edit_profile) do |f| %>
      <fieldset>

        <div class="control-group">
          <%= f.label :name %>
          <div class="controls">
            <%= f.text_field :name, class: 'form-control' %><br /><br />
          </div>
        </div>

        <div class="control-group">
          <%= f.label :age %>
          <div class="controls">
            <%= f.text_field :age,class: 'form-control' %><br /><br />
          </div>
        </div>

        <div class="control-group">
          <%= f.label :about %>
          <div class="controls">
            <%= f.text_field :about,class: 'form-control' %><br /><br />
          </div>
        </div>

        <div class="control-group">

          <div class="controls">
            <%= f.file_field :avatar,class: 'form-control' %><br /><br />
          </div>
        </div>

        <% hidden_field_tag :avatar%>
        <div class="form-actions">
          <%= f.button :submit,:class=>"btn btn-xs btn-success" %>
        </div>
      </fieldset>

  <%end%>
</div>

app/views/users/edit.js.erb
$('#bodydisplay').html("<%= escape_javascript render 'editprofile'%>");

app/views/users/index.html.erb
<div class="container">
    <div class="row header">
      <div class="col-md-2 imageblock">
        <div class="thumbnail">
          <%= image_tag @imagefile.avatar.thumb.url %>
        </div>
      </div>
      <div class="col-md-8 col-md-offset-1 timeline ">
         <div class="row profileblock">
           <div class="row">
              <h4> <%=@user_profile.name%></h4>
           </div>
             <div class="row">
               <h4><%=@user_profile.about%></h4>
             </div>
           </div>
        <hr />

        <%= link_to 'create profile', new_profile_path,:class => "profile" %>
        <%= link_to 'Update Profile', edit_user_path(:id=>@user_profile.id),:remote=>true %>
        <%= link_to 'Index', users_path %>


      </div>
    </div>

  <div id="bodydisplay">


  </div>
     <div id="modaldisplay">
            <div class="modal fade" id="formmodal" tabindex="-1" role="dialog" aria-labelledby="test results" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              </div>
              <h4 class="modal-title">New Post</h4>

              <div class="modal-body">

              </div>
            </div>
          </div>
        </div>

     </div>


</div>

app/views/users/new.html.erb
<h4><strong>sign up</strong></h4>

<%= form_for @new_user do |f| %>
    <div class="control-group">
      <%= f.label :name %>
      <div class="controls">
        <%= f.text_field :name, class: 'form-control' %><br /><br />
      </div>
    </div>

    <div class="control-group">
      <%= f.label :email %>
      <div class="controls">
        <%= f.text_field :email, class: 'form-control' %><br /><br />
      </div>
    </div>

    <div class="control-group">
      <%= f.label :username %>
      <div class="controls">
        <%= f.text_field :username, class: 'form-control' %><br /><br />
      </div>
    </div>

    <div class="control-group">
      <%= f.label :password %>
      <div class="controls">
        <%= f.password_field :password, class: 'form-control' %><br /><br />
      </div>
    </div>

    <div class="control-group">
      <%= f.label :password_confirmation %>
      <div class="controls">
        <%= f.password_field :password_confirmation, class: 'form-control' %><br /><br />
      </div>
    </div>

    <div class="form-actions">
      <%= f.button :submit,:class=>"btn btn-xs btn-success" %>
    </div>
<%end%>

app/views/users/new.js.erb
$('#modaldisplay').html("<%= escape_javascript render 'new_post'%>");
$('#modaldisply').show();